/* eslint-disable */
/* Leaderboard destinations — public model rankings and comparison sites */

LANDSCAPE.leaderboards = [
  // ── LLM Quality ────────────────────────────────────────────────────────
  {
    id: 'chatbot-arena',
    name: 'LMSYS Chatbot Arena',
    shortName: 'Chatbot Arena',
    initials: 'CA',
    logo: 'logos/chatbot-arena.png',
    description:
      'Community-driven leaderboard ranking LLMs by blind human preference votes in head-to-head chat battles. The most cited open benchmark for conversational model quality.',
    category: 'quality',
    types: ['quality'],
    url: 'https://lmarena.ai/?leaderboard',
    org: 'LMSYS / UC Berkeley',
    relatedTools: ['helm', 'lm-eval'],
    metrics: ['Elo rating', 'Win rate', 'Confidence intervals', 'Style control'],
    tags: ['human-preference', 'chat', 'elo', 'arena'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'open-llm-leaderboard',
    name: 'Open LLM Leaderboard',
    shortName: 'Open LLM LB',
    initials: 'OLL',
    logo: 'logos/open-llm-leaderboard.png',
    description:
      'Retired Hugging Face leaderboard that ranked open-weight LLMs across MMLU, ARC, HellaSwag, TruthfulQA, Winogrande, and GSM8K. Historical results remain available; Hugging Face now points users to community-led leaderboards instead.',
    category: 'quality',
    types: ['quality'],
    url: 'https://huggingface.co/docs/leaderboards/en/open_llm_leaderboard/archive',
    org: 'Hugging Face',
    relatedTools: ['lm-eval', 'helm'],
    metrics: ['Average score', 'MMLU', 'ARC', 'HellaSwag', 'TruthfulQA', 'GSM8K'],
    tags: ['huggingface', 'open-models', 'nlp', 'archived'],
    status: 'archived',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'hf-find-a-leaderboard',
    name: 'Hugging Face Find a Leaderboard',
    shortName: 'HF Leaderboards',
    initials: 'HF',
    description:
      'Directory of 200+ community LLM leaderboards on Hugging Face — the recommended starting point for task-specific rankings after the Open LLM Leaderboard retirement.',
    category: 'quality',
    types: ['quality'],
    url: 'https://huggingface.co/spaces/OpenEvals/find-a-leaderboard',
    org: 'Hugging Face / OpenEvals',
    relatedTools: ['lm-eval', 'helm'],
    metrics: ['Community rankings', 'Task-specific scores'],
    tags: ['huggingface', 'directory', 'community'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'helm-leaderboard',
    name: 'HELM Leaderboard',
    shortName: 'HELM LB',
    initials: 'HL',
    logo: 'logos/helm-leaderboard.png',
    description:
      'Stanford CRFM holistic evaluation leaderboard covering accuracy, calibration, robustness, fairness, bias, toxicity, and efficiency across dozens of scenarios.',
    category: 'quality',
    types: ['quality'],
    url: 'https://crfm.stanford.edu/helm/',
    org: 'Stanford CRFM',
    relatedTools: ['helm', 'lm-eval'],
    metrics: ['Accuracy', 'Calibration', 'Robustness', 'Fairness', 'Efficiency'],
    tags: ['stanford', 'holistic', 'multi-metric'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'opencompass-leaderboard',
    name: 'OpenCompass Leaderboard',
    shortName: 'OpenCompass',
    initials: 'OC',
    logo: 'logos/opencompass-leaderboard.png',
    description:
      'Shanghai AI Lab ranking platform covering 100+ benchmarks and 100+ models — one of the most comprehensive multi-benchmark LLM leaderboards, especially for multilingual and Chinese models.',
    category: 'quality',
    types: ['quality', 'multimodal'],
    url: 'https://rank.opencompass.org.cn/home',
    org: 'Shanghai AI Lab',
    relatedTools: ['lm-eval'],
    metrics: ['Composite score', 'Per-benchmark accuracy', 'Multilingual scores'],
    tags: ['opencompass', 'multilingual', 'comprehensive'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'artificial-analysis-models',
    name: 'Artificial Analysis Model Leaderboard',
    shortName: 'Artificial Analysis',
    initials: 'AA',
    logo: 'logos/artificial-analysis.png',
    description:
      'Independent comparison of frontier and open models across intelligence index scores, pricing, latency, and throughput — useful for production model selection.',
    category: 'quality',
    types: ['quality', 'online'],
    url: 'https://artificialanalysis.ai/leaderboards/models',
    org: 'Artificial Analysis',
    relatedTools: ['llmperf', 'inferx'],
    metrics: ['Intelligence index', 'Price per 1M tokens', 'Latency', 'Throughput'],
    tags: ['frontier-models', 'api', 'cost', 'latency'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'livebench',
    name: 'LiveBench',
    shortName: 'LiveBench',
    initials: 'LB',
    description:
      'Contamination-free LLM benchmark with monthly refreshed questions across math, reasoning, coding, language, and instruction-following — designed to prevent training-data leakage.',
    category: 'quality',
    types: ['quality'],
    url: 'https://livebench.ai/',
    org: 'LiveBench Team',
    relatedTools: ['lm-eval', 'helm'],
    metrics: ['Overall score', 'Math', 'Reasoning', 'Coding', 'Language', 'IF'],
    tags: ['contamination-free', 'monthly-refresh'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'eq-bench',
    name: 'EQ-Bench',
    shortName: 'EQ-Bench',
    initials: 'EQ',
    description:
      'Benchmark and leaderboard focused on emotional intelligence in LLMs — measures empathy, social reasoning, and emotional understanding through creative writing tasks.',
    category: 'quality',
    types: ['quality'],
    url: 'https://eqbench.com/',
    org: 'EQ-Bench',
    relatedTools: ['helm', 'lm-eval'],
    metrics: ['EQ score', 'Emotional understanding', 'Social reasoning'],
    tags: ['emotional-intelligence', 'creative-writing'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'alpaca-eval',
    name: 'AlpacaEval Leaderboard',
    shortName: 'AlpacaEval',
    initials: 'AE',
    description:
      'Automatic evaluation leaderboard using GPT-4 as judge to compare instruction-following quality against a reference model. Widely used for fast, cheap model comparisons.',
    category: 'quality',
    types: ['quality'],
    url: 'https://tatsu-lab.github.io/alpaca_eval/',
    org: 'Stanford Tatsu Lab',
    relatedTools: ['lm-eval', 'openai-evals'],
    metrics: ['Win rate vs GPT-4', 'Length-controlled win rate', 'Cost'],
    tags: ['instruction-following', 'llm-judge', 'automatic'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },

  // ── Code ─────────────────────────────────────────────────────────────────
  {
    id: 'swe-bench-leaderboard',
    name: 'SWE-bench Leaderboard',
    shortName: 'SWE-bench LB',
    initials: 'SW',
    logo: 'logos/swe-bench-leaderboard.png',
    description:
      'Official leaderboard for SWE-bench — tracks which AI systems can resolve real GitHub issues end-to-end. The gold standard for autonomous software engineering capability.',
    category: 'code',
    types: ['code'],
    url: 'https://www.swebench.com/',
    org: 'Princeton / Stanford',
    relatedTools: ['swe-bench', 'livecodebench'],
    metrics: ['% Issues resolved', 'Verified', 'Lite', 'Multimodal'],
    tags: ['software-engineering', 'github-issues', 'agents'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'livecodebench-leaderboard',
    name: 'LiveCodeBench Leaderboard',
    shortName: 'LiveCodeBench LB',
    initials: 'LC',
    logo: 'logos/livecodebench-leaderboard.png',
    description:
      'Continuously updated coding benchmark leaderboard with fresh LeetCode, AtCoder, and CodeForces problems to prevent data contamination.',
    category: 'code',
    types: ['code'],
    url: 'https://livecodebench.github.io/leaderboard.html',
    org: 'UC Berkeley / MIT',
    relatedTools: ['livecodebench', 'humaneval'],
    metrics: ['Pass@1', 'Code generation', 'Test output prediction', 'Code repair'],
    tags: ['contamination-free', 'competitive-programming'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'bigcodebench-leaderboard',
    name: 'BigCodeBench Leaderboard',
    shortName: 'BigCodeBench LB',
    initials: 'BC',
    logo: 'logos/bigcodebench-leaderboard.png',
    description:
      'Leaderboard for BigCodeBench — evaluates LLMs on 1,140 diverse Python programming tasks requiring complex library usage and multi-step reasoning. Evaluation repository archived in July 2026; historical rankings remain available.',
    category: 'code',
    types: ['code'],
    url: 'https://bigcode-bench.github.io/',
    org: 'BigCode Project',
    relatedTools: ['bigcodebench', 'humaneval'],
    metrics: ['Pass@1', 'Complete code', 'Self-repair'],
    tags: ['python', 'library-use', 'complex-tasks', 'archived'],
    status: 'archived',
    lastReviewed: '2026-08-24',
  },

  // ── Agents ───────────────────────────────────────────────────────────────
  {
    id: 'bfcl-leaderboard',
    name: 'Berkeley Function Calling Leaderboard',
    shortName: 'BFCL',
    initials: 'BF',
    logo: 'logos/bfcl-leaderboard.png',
    description:
      'Live leaderboard ranking LLM function-calling accuracy across Python, Java, SQL, REST API, and parallel/nested tool invocation scenarios.',
    category: 'agent',
    types: ['agent'],
    url: 'https://gorilla.cs.berkeley.edu/leaderboard.html',
    org: 'UC Berkeley',
    relatedTools: ['bfcl'],
    metrics: ['Overall accuracy', 'Simple', 'Parallel', 'Multiple', 'Irrelevance'],
    tags: ['function-calling', 'tool-use', 'api'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'agentbench-leaderboard',
    name: 'AgentBench Leaderboard',
    shortName: 'AgentBench LB',
    initials: 'AB',
    logo: 'logos/agentbench-leaderboard.png',
    description:
      'THUDM leaderboard evaluating LLM agents across OS interaction, database queries, knowledge graphs, digital card games, and web shopping environments.',
    category: 'agent',
    types: ['agent'],
    url: 'https://agentbench.com/',
    org: 'Tsinghua THUDM',
    relatedTools: ['agentbench'],
    metrics: ['Overall score', 'OS', 'DB', 'KG', 'Digital card game', 'Web shopping'],
    tags: ['multi-environment', 'agent-evaluation'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'webarena-leaderboard',
    name: 'WebArena Leaderboard',
    shortName: 'WebArena LB',
    initials: 'WA',
    logo: 'logos/webarena-leaderboard.png',
    description:
      'Leaderboard for autonomous web agents navigating realistic e-commerce, forum, GitLab, and map sites to complete multi-step tasks.',
    category: 'agent',
    types: ['agent'],
    url: 'https://webarena.dev/',
    org: 'CMU / UCLA',
    relatedTools: ['webarena'],
    metrics: ['Task success rate', 'Step efficiency'],
    tags: ['web-browsing', 'autonomous-agents'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'tau-bench-leaderboard',
    name: 'τ-bench Leaderboard',
    shortName: 'τ-bench LB',
    initials: 'τB',
    logo: 'logos/tau-bench-leaderboard.png',
    description:
      'Sierra Research leaderboard for tool-agent-user interaction in customer service domains — measures agents operating tools while conversing with simulated users.',
    category: 'agent',
    types: ['agent'],
    url: 'https://taubench.com/',
    org: 'Sierra Research',
    relatedTools: ['tau-bench'],
    metrics: ['Pass^k reliability', 'Retail domain', 'Airline domain'],
    tags: ['customer-service', 'tool-use', 'reliability'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'gaia-leaderboard',
    name: 'GAIA Leaderboard',
    shortName: 'GAIA',
    initials: 'GA',
    logo: 'logos/gaia-leaderboard.png',
    description:
      'Hugging Face leaderboard for GAIA — tests whether AI assistants can reason, browse, and use tools to answer real-world questions that are easy for humans but hard for models.',
    category: 'agent',
    types: ['agent', 'quality'],
    url: 'https://huggingface.co/spaces/gaia-benchmark/leaderboard',
    org: 'Meta / Hugging Face',
    relatedTools: ['agentbench'],
    metrics: ['Level 1 accuracy', 'Level 2 accuracy', 'Level 3 accuracy'],
    tags: ['general-assistant', 'tool-use', 'reasoning'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'coding-agent-leaderboard',
    name: 'Coding Agent Leaderboard',
    shortName: 'Coding Agent LB',
    initials: 'CA',
    logo: 'logos/huggingface.png',
    description:
      'Hugging Face leaderboard ranking coding agents across SWE-bench Verified, LiveCodeBench, and other software engineering benchmarks — aggregates results from multiple evaluation sources for unified agent comparison.',
    category: 'agent',
    types: ['code', 'agent'],
    url: 'https://huggingface.co/spaces/taagarwa/coding-agent-leaderboard',
    org: 'Hugging Face',
    relatedTools: ['swe-bench', 'bfcl', 'harbor', 'tau-bench'],
    metrics: ['SWE-bench Verified', 'RH SWE Bench', 'Agent ranking'],
    tags: ['coding-agents', 'software-engineering', 'huggingface', 'aggregated'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },

  // ── RAG & Embeddings ─────────────────────────────────────────────────────
  {
    id: 'mteb-leaderboard',
    name: 'MTEB Leaderboard',
    shortName: 'MTEB LB',
    initials: 'MT',
    logo: 'logos/mteb-leaderboard.png',
    description:
      'Massive Text Embedding Benchmark leaderboard on Hugging Face — ranks embedding models across 56 datasets spanning retrieval, classification, clustering, and semantic similarity.',
    category: 'embedding',
    types: ['embedding', 'rag'],
    url: 'https://huggingface.co/spaces/mteb/leaderboard',
    org: 'MTEB / Hugging Face',
    relatedTools: ['mteb', 'beir'],
    metrics: ['Mean task score', 'Retrieval', 'Classification', 'Clustering', 'STS'],
    tags: ['embeddings', 'retrieval', 'huggingface'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'c-mteb-leaderboard',
    name: 'C-MTEB Leaderboard',
    shortName: 'C-MTEB',
    initials: 'CM',
    description:
      'Chinese Massive Text Embedding Benchmark leaderboard — ranks embedding models on Chinese retrieval, classification, and clustering tasks.',
    category: 'embedding',
    types: ['embedding'],
    url: 'https://huggingface.co/spaces/mteb/leaderboard',
    org: 'MTEB',
    relatedTools: ['mteb'],
    metrics: ['Chinese retrieval', 'Classification', 'Clustering'],
    tags: ['chinese', 'embeddings', 'multilingual'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'air-bench-leaderboard',
    name: 'AIR-Bench Leaderboard',
    shortName: 'AIR-Bench LB',
    initials: 'AR',
    logo: 'logos/air-bench-leaderboard.png',
    description:
      'Leaderboard for AIR-Bench — evaluates embedding and reranking models on diverse, automatically generated retrieval tasks across domains and languages.',
    category: 'embedding',
    types: ['embedding', 'rag'],
    url: 'https://huggingface.co/spaces/AIR-Bench/leaderboard',
    org: 'AIR-Bench',
    relatedTools: ['air-bench-retrieval', 'mteb'],
    metrics: ['nDCG@10', 'Recall@10', 'Per-domain scores'],
    tags: ['retrieval', 'reranking', 'dynamic-tasks'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },

  // ── Audio ────────────────────────────────────────────────────────────────
  {
    id: 'open-asr-leaderboard',
    name: 'Open ASR Leaderboard',
    shortName: 'Open ASR LB',
    initials: 'AS',
    logo: 'logos/open-asr-leaderboard.png',
    description:
      'Hugging Face leaderboard ranking speech-to-text models by Word Error Rate across multiple domains — the primary public comparison for open ASR systems.',
    category: 'audio',
    types: ['audio'],
    url: 'https://huggingface.co/spaces/hf-audio/open_asr_leaderboard',
    org: 'Hugging Face',
    relatedTools: ['whisper-bench', 'esb'],
    metrics: ['WER', 'Per-dataset WER', 'Real-time factor'],
    tags: ['asr', 'speech-to-text', 'wer'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'open-tts-leaderboard',
    name: 'Open TTS Leaderboard',
    shortName: 'Open TTS LB',
    initials: 'TT',
    logo: 'logos/open-tts-leaderboard.png',
    description:
      'Hugging Face leaderboard comparing open text-to-speech models on naturalness, intelligibility, and speaker similarity metrics.',
    category: 'audio',
    types: ['audio'],
    url: 'https://huggingface.co/spaces/hf-audio/open_tts_leaderboard',
    org: 'Hugging Face',
    relatedTools: ['voice-bench'],
    metrics: ['MOS', 'Speaker similarity', 'Intelligibility'],
    tags: ['tts', 'text-to-speech', 'speech-synthesis'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },

  // ── Multimodal ───────────────────────────────────────────────────────────
  {
    id: 'mmmu-leaderboard',
    name: 'MMMU Leaderboard',
    shortName: 'MMMU LB',
    initials: 'MM',
    logo: 'logos/mmmu-leaderboard.png',
    description:
      'Official leaderboard for MMMU — ranks vision-language models on college-level multidisciplinary questions requiring expert knowledge and visual reasoning.',
    category: 'multimodal',
    types: ['multimodal'],
    url: 'https://mmmu-benchmark.github.io/#leaderboard',
    org: 'MMMU Team',
    relatedTools: ['mmmu'],
    metrics: ['Overall accuracy', 'Per-discipline accuracy', 'Per-modality accuracy'],
    tags: ['vision-language', 'college-level', 'reasoning'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'mmbench-leaderboard',
    name: 'MMBench Leaderboard',
    shortName: 'MMBench LB',
    initials: 'MB',
    logo: 'logos/mmbench-leaderboard.png',
    description:
      'OpenCompass MMBench leaderboard with CircularEval — ranks VLMs across 20 fine-grained perception and reasoning capability dimensions.',
    category: 'multimodal',
    types: ['multimodal'],
    url: 'https://mmbench.opencompass.org.cn/leaderboard',
    org: 'Shanghai AI Lab',
    relatedTools: ['mmbench'],
    metrics: ['Overall score', 'Perception', 'Reasoning', 'Per-dimension accuracy'],
    tags: ['vision-language', 'fine-grained', 'circular-eval'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'seed-bench-leaderboard',
    name: 'SEED-Bench Leaderboard',
    shortName: 'SEED LB',
    initials: 'SD',
    logo: 'logos/seed-bench-leaderboard.png',
    description:
      'Leaderboard for SEED-Bench — compares image and video understanding models across 12 evaluation dimensions including spatial and temporal reasoning.',
    category: 'multimodal',
    types: ['multimodal'],
    url: 'https://huggingface.co/spaces/AILab-CVC/SEED-Bench_Leaderboard',
    org: 'Tencent ARC',
    relatedTools: ['seed-bench'],
    metrics: ['Image accuracy', 'Video accuracy', 'Per-dimension score'],
    tags: ['video', 'image-understanding', 'tencent'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'open-vlm-leaderboard',
    name: 'Open VLM Leaderboard',
    shortName: 'Open VLM LB',
    initials: 'VL',
    logo: 'logos/open-vlm-leaderboard.png',
    description:
      'Hugging Face leaderboard aggregating vision-language model scores across VQA, OCR, chart understanding, and document AI benchmarks.',
    category: 'multimodal',
    types: ['multimodal'],
    url: 'https://huggingface.co/spaces/opencompass/open_vlm_leaderboard',
    org: 'OpenCompass / Hugging Face',
    relatedTools: ['mmbench', 'mmmu'],
    metrics: ['Average score', 'VQA', 'OCR', 'Chart QA', 'Doc QA'],
    tags: ['vision-language', 'open-models', 'huggingface'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },

  // ── Inference ────────────────────────────────────────────────────────────
  {
    id: 'mlperf-results',
    name: 'MLPerf Inference Results',
    shortName: 'MLPerf Results',
    initials: 'MP',
    logo: 'logos/mlperf-results.png',
    description:
      'Official MLCommons published inference benchmark results across datacenter, edge, and mobile categories — the industry-standard hardware and model performance comparison.',
    category: 'inference',
    types: ['online', 'offline'],
    url: 'https://mlcommons.org/benchmarks/inference/',
    org: 'MLCommons',
    relatedTools: ['mlperf'],
    metrics: ['Throughput', 'Latency', 'Power efficiency', 'Per-category results'],
    tags: ['mlcommons', 'industry-standard', 'hardware'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'artificial-analysis-inference',
    name: 'Artificial Analysis Inference Leaderboard',
    shortName: 'AA Inference',
    initials: 'AI',
    logo: 'logos/artificial-analysis.png',
    description:
      'Live API inference comparison across providers — tracks output speed (tokens/s), time to first token, and price for frontier and open models.',
    category: 'inference',
    types: ['online'],
    url: 'https://artificialanalysis.ai/models',
    org: 'Artificial Analysis',
    relatedTools: ['llmperf', 'inferx', 'vllm-serve'],
    metrics: ['Output speed (tok/s)', 'TTFT', 'Price per 1M tokens', 'Context window'],
    tags: ['api', 'latency', 'throughput', 'cost'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'inferencex-dashboard',
    name: 'InferenceX Dashboard',
    shortName: 'InferenceX',
    initials: 'IX',
    logo: 'logos/inferencex-dashboard.png',
    description:
      'SemiAnalysis interactive dashboard comparing LLM inference throughput, latency, and cost efficiency across GPU hardware, frameworks, and quantization strategies.',
    category: 'inference',
    types: ['online', 'offline'],
    url: 'https://inferencex.ai/',
    org: 'SemiAnalysis',
    relatedTools: ['inferx'],
    metrics: ['Throughput (tok/s)', 'Latency percentiles', 'Cost per million tokens', 'Hardware efficiency'],
    tags: ['semianalysis', 'gpu', 'cost', 'frameworks'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },

  // ── LLM Routing ────────────────────────────────────────────────────────
  {
    id: 'routerarena-leaderboard',
    name: 'RouterArena Leaderboard',
    shortName: 'RouterArena',
    initials: 'RA',
    description:
      'Live leaderboard and submission platform for LLM routers — evaluates open-source and commercial routers on 8,400 questions across nine domains with accuracy, cost, optimality, robustness, and latency metrics.',
    category: 'model-routing',
    types: ['online'],
    url: 'https://routeworks.github.io/',
    org: 'RouteWorks',
    relatedTools: ['routerbench', 'llmrouterbench', 'routellm', 'vllm-semantic-router'],
    metrics: ['Arena score', 'Accuracy', 'Cost per 1k queries', 'Optimal selection', 'Robustness', 'Latency'],
    tags: ['routing', 'llm-router', 'cost', 'leaderboard', 'arena'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },

  // ── Safety & Security ────────────────────────────────────────────────────
  {
    id: 'harmbench-leaderboard',
    name: 'HarmBench Leaderboard',
    shortName: 'HarmBench LB',
    initials: 'HB',
    logo: 'logos/harmbench-leaderboard.png',
    description:
      'Center for AI Safety leaderboard ranking model robustness against automated red-teaming attacks across harmful behaviors, copyright, and misinformation.',
    category: 'safety',
    types: ['safety', 'security'],
    url: 'https://www.harmbench.org/',
    org: 'Center for AI Safety',
    relatedTools: ['harmbench', 'garak'],
    metrics: ['Attack success rate', 'Per-behavior robustness', 'Red-team method comparison'],
    tags: ['red-teaming', 'safety', 'robustness'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'salad-bench-leaderboard',
    name: 'SALAD-Bench Leaderboard',
    shortName: 'SALAD LB',
    initials: 'SA',
    logo: 'logos/salad-bench-leaderboard.png',
    description:
      'Safety assessment leaderboard evaluating LLMs across attack, defense, and general safety dimensions with fine-grained harm categories.',
    category: 'safety',
    types: ['safety'],
    url: 'https://salad-bench.github.io/',
    org: 'OpenSafetyLab',
    relatedTools: ['salad-bench'],
    metrics: ['Attack success rate', 'Defense rate', 'Per-category safety score'],
    tags: ['safety', 'attack-defense', 'fine-grained'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
  {
    id: 'cyberseceval-leaderboard',
    name: 'CyberSecEval Leaderboard',
    shortName: 'CyberSecEval LB',
    initials: 'CS',
    logo: 'logos/cyberseceval-leaderboard.png',
    description:
      'Meta Purple Llama cybersecurity benchmark leaderboard — ranks models on insecure code generation, cyberattack assistance, and prompt injection resistance.',
    category: 'security',
    types: ['security'],
    url: 'https://meta-llama.github.io/PurpleLlama/CyberSecEval/',
    org: 'Meta / Purple Llama',
    relatedTools: ['cyberseceval'],
    metrics: ['Insecure code rate', 'Attack compliance', 'Prompt injection success'],
    tags: ['cybersecurity', 'code-security', 'meta'],
    status: 'active',
    lastReviewed: '2026-08-24',
  },
];

LANDSCAPE.leaderboards.forEach((lb) => {
  lb.status = lb.status || 'active';
  lb.lastReviewed = lb.lastReviewed || '2026-08-12';
  lb.useCases = lb.useCases || ['leaderboard', 'research'];
  lb.relatedTools = lb.relatedTools || [];
});
